Repository Leets-Official/BOOKMARK-FE, pull requests merged in 2025-08, with the labels that each got.

#85 [Feat] 계정 탈퇴 API 구현
  src/api/users/user.ts
  src/components/ui/HomeLogo.tsx
  src/components/ui/card/FolderCard.tsx
  src/pages/myPage/ProfileEdit.tsx
Labels: 📡 API, ✨Feature

#94 [Feat] #93 CompactCard 및 Alarm 디자인 반영
  src/components/ui/card/CompactCard.tsx
  src/components/ui/card/SaveCard.tsx
  src/components/ui/cardList/SaveCardList.tsx
  src/pages/SearchResult.tsx
  src/types/components/components.ts
Labels: 🎨 Style, ✨Feature

#101 [Feat] # AI 태그 API & 수정 API & 알람 API 구현
  package-lock.json
  package.json
  src/agent/TagAgent.tsx
  src/api/bookmark/bookmark.ts
  src/api/file/thumbnail_api.ts
  src/api/tag/tag.ts
  src/atoms.ts
  src/components/common/Image.tsx
  src/components/layout/dropDown/DateTimeDropDown.tsx
  src/components/layout/footer/HomeFooter.tsx
  src/components/layout/header/CardListHeader.tsx
  src/components/layout/searchBar/ChangeSearchBar.tsx
  src/components/layout/searchBar/SearchBar.tsx
  src/components/ui/TextField.tsx
  src/components/ui/card/FolderCard.tsx
  src/components/ui/card/LinkCard.tsx
  src/components/ui/card/SaveCard.tsx
  src/components/ui/cardLink/Alarm.tsx
  src/components/ui/cardLink/LinkField.tsx
  src/components/ui/cardLink/Memo.tsx
  src/components/ui/cardLink/SaveButton.tsx
  src/components/ui/cardLink/index.tsx
  src/components/ui/cardList/CardList.tsx
  src/components/ui/cardList/MobileCardList.tsx
  src/components/ui/cardList/SaveCardList.tsx
  src/constants/dataFormat.ts
  src/constants/dateTimeData.ts
  src/hooks/date/dateTimeData.ts
  src/hooks/date/formatVisableDate.ts
  src/hooks/submit.ts
  src/pages/Home.tsx
  src/pages/Save.tsx
  src/pages/SearchResult.tsx
  src/schema/save.ts
  src/types/api/bookmark.ts
  src/types/api/category.ts
  src/utils/S3PresignedImage.ts
Labels: 🐛 bug, 📡 API, ✨Feature

#105 [Fix] #105 추가 디자인 및 기능 수정
  src/components/common/Chip.tsx
  src/components/layout/footer/HomeFooter.tsx
  src/components/layout/header/CardListHeader.tsx
  src/components/ui/card/CategoryCard.tsx
  src/components/ui/card/FolderCard.tsx
  src/components/ui/card/SaveCard.tsx
  src/components/ui/cardList/CardList.tsx
  src/components/ui/cardList/SaveCardList.tsx
  src/pages/Search.tsx
  src/pages/myPage/MyPage.tsx
Labels: 🐛 bug, 🔧 Chore, 🎨 Style

#109 [Fix] #108 Search Result 페이지에 태그 오류 수정
  src/pages/SearchResult.tsx
  src/pages/myPage/MyPage.tsx
Labels: 🐛 bug

#111 [Feat] #110 Platform DropDown
  src/components/common/Chip.tsx
  src/components/layout/dropDown/ChipDropDown.tsx
  src/pages/SearchResult.tsx
  src/types/components/components.ts
Labels: ✨Feature
